# Generated by Django 4.2.30 on 2026-07-19 21:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=100, verbose_name="Имя гостя"),
                ),
                (
                    "guest_phone",
                    models.CharField(max_length=20, verbose_name="Телефон гостя"),
                ),
                (
                    "party_size",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество персон",
                    ),
                ),
                (
                    "booking_datetime",
                    models.DateTimeField(verbose_name="Дата и время визита"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Пожелания")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Сумма чека (₽)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bezluka_web", "Сайт БезЛука"),
                            ("thefork", "TheFork"),
                            ("leclick", "LeClick"),
                            ("tomesto", "ТоМесто"),
                            ("allcafe", "Allcafe"),
                            ("restoclub", "Restoclub"),
                            ("restorating", "Restorating"),
                            ("restoran_ru", "Restoran.ru"),
                            ("afisha", "Afisha"),
                            ("opentable", "OpenTable"),
                            ("resy", "Resy"),
                            ("quandoo", "Quandoo"),
                            ("smartreserve", "Smartreserve"),
                            ("remarked", "Remarked"),
                            ("hostme", "Hostme"),
                            ("phone", "Телефон"),
                        ],
                        max_length=30,
                        verbose_name="Источник брони",
                    ),
                ),
                (
                    "external_booking_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Внешний ID брони",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("rejected", "Отклонено"),
                            ("cancelled_by_user", "Отменено гостем"),
                            ("cancelled_by_restaurant", "Отменено рестораном"),
                            ("completed", "Состоялось"),
                            ("no_show", "Не пришел"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-booking_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название события"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "event_datetime",
                    models.DateTimeField(db_index=True, verbose_name="Дата и время"),
                ),
                (
                    "image_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Постер"),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Макс. участников",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["-event_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название меню"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Категория")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.menu",
                        verbose_name="Меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория меню",
                "verbose_name_plural": "Категории меню",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Название юр. лица / ИП",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Должность"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль владельца",
                "verbose_name_plural": "Профили владельцев",
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Скидка (₽)",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Начало действия")),
                ("valid_until", models.DateTimeField(verbose_name="Окончание")),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Макс. использований",
                    ),
                ),
                (
                    "current_uses",
                    models.IntegerField(default=0, verbose_name="Текущее кол-во"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название ресторана"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-слаб (ЧПУ)"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "coordinates",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Координаты (широта, долгота)",
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(max_length=100, verbose_name="Тип кухни"),
                ),
                (
                    "avg_check",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Средний чек (₽)",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(max_length=100, verbose_name="График работы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон ресторана"),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Главное фото"
                    ),
                ),
                (
                    "external_ids",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Внешние ID для интеграций",
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Общий рейтинг",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="Количество отзывов"),
                ),
                (
                    "return_rate",
                    models.IntegerField(default=0, verbose_name="Возвращаемость (%)"),
                ),
                (
                    "recommend_rate",
                    models.IntegerField(default=0, verbose_name="Рекомендуют (%)"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активен (виден в приложении)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="core.ownerprofile",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("code", models.CharField(max_length=10, verbose_name="Код")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, verbose_name="Попыток ввода"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Код подтверждения",
                "verbose_name_plural": "Коды подтверждения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("waiter", "Официант"),
                            ("senior_waiter", "Старший официант"),
                            ("bartender", "Бармен"),
                            ("chef", "Шеф-повар"),
                            ("cook", "Повар"),
                            ("admin", "Администратор"),
                        ],
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="Опыт работы (лет)"),
                ),
                (
                    "photo_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Фото"),
                ),
                (
                    "csat_score",
                    models.IntegerField(default=0, verbose_name="Рейтинг CSAT (%)"),
                ),
                (
                    "complaints_count",
                    models.IntegerField(default=0, verbose_name="Количество жалоб"),
                ),
                (
                    "badges_count",
                    models.IntegerField(default=0, verbose_name="Получено бейджей"),
                ),
                (
                    "tips_total",
                    models.IntegerField(default=0, verbose_name="Сумма чаевых (₽)"),
                ),
                (
                    "reviews_count",
                    models.IntegerField(default=0, verbose_name="Количество отзывов"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="core.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Только ресторан"),
                            ("staff", "Только сотрудник"),
                            ("both", "И ресторан, и сотрудник"),
                        ],
                        default="restaurant",
                        max_length=15,
                        verbose_name="Тип отзыва",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка (1-5)",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст отзыва")),
                (
                    "is_moderated",
                    models.BooleanField(default=False, verbose_name="Прошел модерацию"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="core.staffmember",
                        verbose_name="Оцененный сотрудник",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booking", "Бронирование"),
                            ("promo", "Промоакция"),
                            ("loyalty", "Лояльность"),
                            ("system", "Системное"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название блюда"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена (₽)",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL фото"
                    ),
                ),
                ("is_popular", models.BooleanField(default=False, verbose_name="Хит")),
                ("is_new", models.BooleanField(default=False, verbose_name="Новинка")),
                (
                    "is_chef_recommended",
                    models.BooleanField(default=False, verbose_name="Шеф рекомендует"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="В наличии"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.menucategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блюдо",
                "verbose_name_plural": "Блюда",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="core.restaurant",
                verbose_name="Ресторан",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_change",
                    models.IntegerField(verbose_name="Изменение баллов (+/-)"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("registration", "Приветственные баллы"),
                            ("booking_cashback", "Кэшбэк за бронь"),
                            ("review", "Бонус за отзыв"),
                            ("referral", "Реферальный бонус"),
                            ("cancellation", "Возврат при отмене"),
                            ("redemption", "Списание баллов"),
                            ("manual", "Ручная корректировка"),
                        ],
                        max_length=30,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время операции"
                    ),
                ),
                (
                    "related_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.booking",
                        verbose_name="Связанная бронь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция лояльности",
                "verbose_name_plural": "Транзакции лояльности",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GuestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=15, verbose_name="Пол"),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(
                        default=False, verbose_name="Согласие на рассылки (152-ФЗ)"
                    ),
                ),
                (
                    "total_bookings",
                    models.IntegerField(default=0, verbose_name="Всего броней"),
                ),
                (
                    "completed_bookings",
                    models.IntegerField(default=0, verbose_name="Состоявшихся броней"),
                ),
                (
                    "cancelled_bookings",
                    models.IntegerField(default=0, verbose_name="Отменённых броней"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Общая сумма трат (₽)",
                    ),
                ),
                (
                    "monthly_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Траты за текущий месяц (₽)",
                    ),
                ),
                (
                    "reputation_score",
                    models.IntegerField(default=0, verbose_name="Репутация (0-100)"),
                ),
                (
                    "cashback_percent",
                    models.IntegerField(default=2, verbose_name="Кэшбэк % (2-10%)"),
                ),
                (
                    "loyalty_level",
                    models.CharField(
                        choices=[
                            ("Select", "Select"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Platinum", "Platinum"),
                        ],
                        default="Select",
                        max_length=10,
                        verbose_name="Уровень лояльности",
                    ),
                ),
                (
                    "points_balance",
                    models.IntegerField(
                        default=500, verbose_name="Баланс баллов (500 приветственных)"
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Реферальный код",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="core.guestprofile",
                        verbose_name="Пришёл по рефералу от",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль гостя",
                "verbose_name_plural": "Профили гостей",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="core.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Гость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Зарегистрирован"),
                            ("attended", "Присутствовал"),
                            ("cancelled", "Отменено"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.event",
                        verbose_name="Событие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Гость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация на событие",
                "verbose_name_plural": "Регистрации на события",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.restaurant",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.restaurant",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Гость",
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Название (Дом, Работа)"
                    ),
                ),
                (
                    "full_address",
                    models.CharField(max_length=255, verbose_name="Полный адрес"),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Координаты"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP-адрес")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Вход в систему"),
                            ("logout", "Выход из системы"),
                            ("view_pd", "Просмотр персональных данных"),
                            ("export", "Экспорт данных"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "target_object",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Объект доступа"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Детали")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто совершил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог доступа",
                "verbose_name_plural": "Логи доступа",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserPromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Активирован"),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.promocode",
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод пользователя",
                "verbose_name_plural": "Промокоды пользователей",
                "unique_together": {("user", "promo_code")},
            },
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["city", "cuisine_type"], name="core_restau_city_4691e6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "restaurant")},
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["restaurant", "booking_datetime"],
                name="core_bookin_restaur_87d0c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "booking_datetime"],
                name="core_bookin_status_75fa88_idx",
            ),
        ),
    ]
