# Generated by Django 4.2.30 on 2026-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="current_noise_level",
            field=models.IntegerField(
                default=0, verbose_name="Текущий уровень шума (%)"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="current_occupancy",
            field=models.IntegerField(
                default=0, verbose_name="Текущая загруженность (%)"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="current_service_time",
            field=models.IntegerField(
                default=0, verbose_name="Текущее время обслуживания (мин)"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="features",
            field=models.TextField(blank=True, verbose_name="Фишки заведения"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="kitchen_hours",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Часы работы кухни"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="match_percent",
            field=models.IntegerField(default=0, verbose_name="Вам подходит (%)"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="recommend_count",
            field=models.IntegerField(default=0, verbose_name="Людей рекомендует"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="staff_atmosphere_rating",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=3, verbose_name="Атмосфера"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="staff_price_quality_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=3,
                verbose_name="Соответствие цена/качество",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="staff_service_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=3,
                verbose_name="Качество обслуживания",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Подзаголовок/слоган"
            ),
        ),
    ]
