# Generated by Django 4.2.30 on 2026-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_restaurant_current_noise_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="atmosphere_rating",
            field=models.IntegerField(default=5, verbose_name="Атмосфера"),
        ),
        migrations.AddField(
            model_name="review",
            name="price_quality_rating",
            field=models.IntegerField(
                default=5, verbose_name="Соответствие цена/качество"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="service_rating",
            field=models.IntegerField(default=5, verbose_name="Качество обслуживания"),
        ),
    ]
