# Generated by Django 4.2.30 on 2026-07-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review_atmosphere_rating_review_price_quality_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="gallery_images",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ссылки на фото галереи"
            ),
        ),
    ]
